#!/bin/sh
# tests/coverage_summary.sh — collect gcov + luacov artefacts into
# build-coverage/, print a summary, refresh manifest/coverage-latest.md.
#
# Runs INSIDE the luafan2-ci:local container (invoked by run_tests.sh
# --coverage). Assumes CWD is the project root.
#
# Exit code:
#   0  summary generated
#   2  --enforce and one of the thresholds not met
#
# Layout:
#   build-coverage/
#     coverage.info            raw + filtered lcov info
#     coverage-html/           genhtml output (open index.html)
#     luacov.stats.out         luacov raw stats (also configured in .luacov)
#     luacov.report.out        luacov's plaintext report
#     summary.txt              short human-readable numbers
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BUILD_DIR="${1:-$ROOT/build-coverage}"
ENFORCE="${2:-0}"

C_MIN=85    # C line-coverage floor (percent)
LUA_MIN=90  # Lua line-coverage floor (percent)

cd "$ROOT"
mkdir -p "$BUILD_DIR"

# ---------------------------------------------------------------------------
# C coverage via lcov.
#
# 1. capture: read every .gcda under BUILD_DIR against the .gcno emitted
#    at compile time. --rc branch_coverage=1 keeps branch data if we ever
#    want it later (we currently only enforce line coverage).
# 2. filter: strip system headers + our own tests + third-party trees so
#    the number reflects project source only.
# 3. genhtml + summary line.
# ---------------------------------------------------------------------------
echo "=== C coverage (lcov) ==="
lcov --directory "$BUILD_DIR" --capture \
     --output-file "$BUILD_DIR/coverage.info.raw" \
     --rc lcov_branch_coverage=1 \
     --quiet 2>&1 | tail -5 || true

lcov --remove "$BUILD_DIR/coverage.info.raw" \
     '/usr/*' '*/tests/*' '*/build*/*' \
     --output-file "$BUILD_DIR/coverage.info" \
     --rc lcov_branch_coverage=1 \
     --quiet 2>&1 | tail -5 || true

genhtml "$BUILD_DIR/coverage.info" \
        --output-directory "$BUILD_DIR/coverage-html" \
        --quiet --legend --title "luafan2 C coverage" 2>&1 | tail -5 || true

# Extract line% from lcov's `--summary` output. Format looks like:
#   lines......: 87.3% (1234 of 1414 lines)
C_LINE_PCT="$(lcov --summary "$BUILD_DIR/coverage.info" 2>&1 \
              | awk '/lines/ { for(i=1;i<=NF;i++) if($i ~ /%$/) { print $i; exit } }' \
              | tr -d '%')"
[ -n "$C_LINE_PCT" ] || C_LINE_PCT="0"
echo "C line coverage: ${C_LINE_PCT}%"

# ---------------------------------------------------------------------------
# Lua coverage via luacov.
#
# luacov's report reads .luacov (project root) + luacov.stats.out and
# writes luacov.report.out. The report's last non-empty summary line is
# the aggregate we care about.
# ---------------------------------------------------------------------------
echo
echo "=== Lua coverage (luacov) ==="
if [ -f "$BUILD_DIR/luacov.stats.out" ]; then
    # Run luacov from project root so .luacov + include patterns resolve.
    luacov 2>&1 | tail -5 || true
    # The default luacov reporter prints a "Total" table at the very end.
    # Grab its overall percentage.
    LUA_LINE_PCT="$(awk '
        /^Total[[:space:]]/ { pct=$NF; gsub("%","",pct); }
        END { if (pct != "") print pct; else print "0" }
    ' "$BUILD_DIR/luacov.report.out")"
    [ -n "$LUA_LINE_PCT" ] || LUA_LINE_PCT="0"
    echo "Lua line coverage: ${LUA_LINE_PCT}%"
else
    echo "no luacov.stats.out found -> Lua coverage: 0%"
    LUA_LINE_PCT="0"
fi

# ---------------------------------------------------------------------------
# Human summary + manifest snapshot.
# ---------------------------------------------------------------------------
{
    echo "luafan2 coverage summary  ($(date -u +%Y-%m-%dT%H:%M:%SZ))"
    echo "C   line coverage: ${C_LINE_PCT}%   (target ${C_MIN}%)"
    echo "Lua line coverage: ${LUA_LINE_PCT}% (target ${LUA_MIN}%)"
    echo "HTML: ${BUILD_DIR}/coverage-html/index.html"
    echo "Lua report: ${BUILD_DIR}/luacov.report.out"
} | tee "$BUILD_DIR/summary.txt"

# Manifest snapshot: only the numbers, so the file is small and diff-able.
{
    echo "# Coverage — latest run"
    echo
    echo "_Auto-generated by \`tests/coverage_summary.sh\`; commit whenever it changes._"
    echo
    echo "| Layer | Line coverage | Target |"
    echo "|-------|---------------|--------|"
    echo "| C     | ${C_LINE_PCT}%   | ${C_MIN}% |"
    echo "| Lua   | ${LUA_LINE_PCT}% | ${LUA_MIN}% |"
    echo
    echo "Timestamp (UTC): $(date -u +%Y-%m-%dT%H:%M:%SZ)"
} > "$ROOT/manifest/coverage-latest.md"

# ---------------------------------------------------------------------------
# Threshold gate (soft warn by default; hard fail under --enforce).
# ---------------------------------------------------------------------------
RC=0
below_min() {
    # awk-based float compare to avoid needing bc.
    awk -v v="$1" -v m="$2" 'BEGIN { exit !(v+0 < m+0) }'
}

if below_min "$C_LINE_PCT" "$C_MIN"; then
    echo "warn: C coverage ${C_LINE_PCT}% < ${C_MIN}%"
    [ "$ENFORCE" = "1" ] && RC=2
fi
if below_min "$LUA_LINE_PCT" "$LUA_MIN"; then
    echo "warn: Lua coverage ${LUA_LINE_PCT}% < ${LUA_MIN}%"
    [ "$ENFORCE" = "1" ] && RC=2
fi

exit $RC
