-- test_objectbuf_v1_interop.lua — LuaFan v1 <-> v2 objectbuf compatibility.
--
-- The fixture tests/fixtures/objectbuf/v1_vectors.lua is generated by the
-- genuine LuaFan v1 runtime (docker image luafan/luafan-ubuntu) running
-- tests/fixtures/objectbuf/probe_emit.lua. For a broad corpus it records:
--   plain  : hex(v1 objectbuf.encode(value))
--   sym    : hex(v1 objectbuf.encode(value, v1 objectbuf.symbol(value)))
--   symtab : hex(v1 objectbuf.encode(v1 objectbuf.symbol(value)))
--   stable : 1 => re-encoding the decoded value must reproduce the exact bytes
--   opaque : 1 => value contains a table used as a key (identity-based compare
--                 is meaningless; byte-exactness is still checked)
--
-- This test proves the v2 native C codec reads every v1 byte stream -- plain
-- and symbol-compressed -- and that byte-stable records re-encode to exactly
-- the same v1 bytes. The live arm1 probe verifies the reverse direction
-- (v2 bytes decoded by the v1 runtime).
--
-- Regenerate with:
--   docker run --rm -v $PWD:/p --entrypoint /usr/local/bin/lua \
--     luafan/luafan-ubuntu /p/tests/fixtures/objectbuf/probe_emit.lua \
--     > tests/fixtures/objectbuf/v1_vectors.lua

local T = require("test_framework")
local fan = require("fan")
local buf = require("fan.objectbuf")

local s = T.suite("fan.objectbuf v1 interop (M5)")

local function fixture_path()
  local here = arg and arg[0]
  if here and here:find("/", 1, true) then
    local dir = here:match("^(.*)/[^/]*$")
    return dir .. "/../fixtures/objectbuf/v1_vectors.lua"
  end
  return "tests/fixtures/objectbuf/v1_vectors.lua"
end

local function unhex(hex)
  return (hex:gsub("%x%x", function(h) return string.char(tonumber(h, 16)) end))
end

local function hex_of(s)
  return (s:gsub(".", function(c) return string.format("%02x", c:byte()) end))
end

local function deep_equal(a, b, seen)
  if type(a) ~= type(b) then return false end
  if type(a) ~= "table" then return a == b end
  seen = seen or {}
  if seen[a] and seen[a][b] then return true end
  seen[a] = seen[a] or {}
  seen[a][b] = true
  for k, v in pairs(a) do
    if not deep_equal(v, b[k], seen) then return false end
  end
  for k in pairs(b) do
    if a[k] == nil then return false end
  end
  return true
end

local records = assert(loadfile(fixture_path()))()

s:test("fixture carries the full cross-version corpus", function()
  T.truthy(#records >= 60, "expected at least 60 v1 vectors, got " .. #records)
end)

s:test("decodes every v1 plain byte stream losslessly", function()
  for _, rec in ipairs(records) do
    local obj = buf.decode(unhex(rec.plain))
    T.not_nil(obj, rec.name .. ": v1 plain decode failed")
    if rec.opaque == 0 then
      T.truthy(deep_equal(obj, buf.decode(buf.encode(obj))),
               rec.name .. ": plain re-encode mismatch")
    end
  end
end)

s:test("byte-stable v1 plain streams re-encode identically", function()
  for _, rec in ipairs(records) do
    if rec.stable == 1 then
      local obj = buf.decode(unhex(rec.plain))
      T.eq(hex_of(buf.encode(obj)), rec.plain, rec.name .. ": plain bytes differ")
    end
  end
end)

s:test("decodes v1 symbol streams using the v1 symbol table", function()
  for _, rec in ipairs(records) do
    if rec.sym ~= "" then
      local sym = buf.decode(unhex(rec.symtab))
      T.not_nil(sym, rec.name .. ": v1 symbol table decode failed")
      local obj = buf.decode(unhex(rec.sym), sym)
      T.not_nil(obj, rec.name .. ": v1 symbol decode failed")
      local reenc = buf.encode(obj, sym)
      if rec.stable == 1 then
        T.eq(hex_of(reenc), rec.sym, rec.name .. ": symbol bytes differ")
      end
      if rec.opaque == 0 then
        T.truthy(deep_equal(obj, buf.decode(reenc, sym)),
                 rec.name .. ": symbol re-encode mismatch")
      end
    end
  end
end)

s:test("v1 symbols actually compress repeated values", function()
  local value = { users = {} }
  for i = 1, 200 do
    value.users[i] = { status = "active", role = "member", region = "eu", id = i }
  end
  local sym = buf.symbol(value)
  T.truthy(#buf.encode(value, sym) < #buf.encode(value),
           "symbol table must reduce wire size")
end)

os.exit(T.run(s))
